from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('timetable/', views.timetable_view, name='timetable'),
    path('timetable/download/', views.timetable_download, name='timetable_download'),
    path('conflicts/', views.conflict_view, name='conflicts'),
    path('generate/', views.generate_timetable, name='generate'),
    path('algorithm/', views.algorithm_report, name='algorithm'),
    path('reschedule/', views.reschedule_request, name='reschedule'),
    path('reschedule/<int:pk>/approve/', views.approve_reschedule, name='approve_reschedule'),
    path('reschedule/<int:pk>/reject/', views.reject_reschedule, name='reject_reschedule'),
    path('lecturers/', views.lecturer_list, name='lecturers'),
    path('lecturers/add/', views.lecturer_edit, name='lecturer_add'),
    path('lecturers/<int:pk>/edit/', views.lecturer_edit, name='lecturer_edit'),
    path('lecturers/<int:pk>/delete/', views.lecturer_delete, name='lecturer_delete'),
    path('lecturers/<int:pk>/create-account/', views.lecturer_create_account, name='lecturer_create_account'),
    path('courses/', views.course_list, name='courses'),
    path('courses/add/', views.course_edit, name='course_add'),
    path('courses/<int:pk>/edit/', views.course_edit, name='course_edit'),
    path('courses/<int:pk>/delete/', views.course_delete, name='course_delete'),
    path('rooms/', views.room_list, name='rooms'),
    path('rooms/add/', views.room_edit, name='room_add'),
    path('rooms/<int:pk>/edit/', views.room_edit, name='room_edit'),
    path('rooms/<int:pk>/delete/', views.room_delete, name='room_delete'),
    path('student-groups/', views.studentgroup_list, name='studentgroups'),
    path('student-groups/add/', views.studentgroup_edit, name='studentgroup_add'),
    path('student-groups/<int:pk>/edit/', views.studentgroup_edit, name='studentgroup_edit'),
    path('student-groups/<int:pk>/delete/', views.studentgroup_delete, name='studentgroup_delete'),
    path('timeslots/', views.timeslot_list, name='timeslots'),
    path('timeslots/add/', views.timeslot_edit, name='timeslot_add'),
    path('timeslots/<int:pk>/edit/', views.timeslot_edit, name='timeslot_edit'),
    path('timeslots/<int:pk>/delete/', views.timeslot_delete, name='timeslot_delete'),
    path('<str:kind>/delete-all/', views.bulk_delete, name='bulk_delete'),
    path('import/', views.data_import, name='data_import'),
    path('import/template/<str:kind>/', views.data_import_template, name='data_import_template'),
    path('students/', views.student_list, name='students'),
    path('students/add/', views.student_edit, name='student_add'),
    path('students/<int:pk>/edit/', views.student_edit, name='student_edit'),
    path('students/<int:pk>/delete/', views.student_delete, name='student_delete'),
    path('students/<int:pk>/create-account/', views.student_create_account, name='student_create_account'),
    path('view-as/<int:pk>/', views.view_as, name='view_as'),
    path('view-as/stop/', views.stop_view_as, name='stop_view_as'),
    path('account/', views.my_account, name='my_account'),
    path('notifications/', views.notification_list, name='notifications'),
    path('notifications/mark-read/', views.notifications_mark_read, name='notifications_mark_read'),
]