"""
Django settings for kts project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import re
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-do-not-use-in-production'
    else:
        raise RuntimeError('SECRET_KEY environment variable must be set in production.')

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS if h not in ('localhost', '127.0.0.1')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'scheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # After authentication, so the real signed-in account is known before the
    # preview swaps it.
    'scheduler.middleware.ImpersonationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kts.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'scheduler.permissions.role_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'kts.wsgi.application'


# Reading settings out of the environment. Defined up here because the
# database configuration below is the first thing that needs them.
def _env_int(name, default):
    """Read a whole number from the environment, tolerating an empty value.

    A dashboard makes it easy to add a key and save before typing the value,
    or to clear one while leaving it in place. int('') raises, and because
    this runs while the settings module is still being imported, that failure
    takes down every page on the site rather than the one feature the setting
    belongs to - a bare "Internal Server Error" everywhere, with the cause
    nowhere near it. An absent value and a blank one mean the same thing here.
    """
    raw = (os.environ.get(name) or '').strip()
    if not raw:
        return default
    try:
        return int(raw)
    except ValueError:
        raise RuntimeError(
            f'{name} must be a whole number, or left unset to use {default}. '
            f'It is currently {raw!r}.'
        ) from None


def _env_bool(name, default):
    """Read a flag, treating an empty value as absent for the same reason.

    Comparing against 'True' would quietly read a blank as False, which for
    EMAIL_USE_TLS means silently dropping TLS rather than reporting anything.
    """
    raw = (os.environ.get(name) or '').strip().lower()
    if not raw:
        return default
    if raw in ('true', '1', 'yes', 'on'):
        return True
    if raw in ('false', '0', 'no', 'off'):
        return False
    raise RuntimeError(
        f'{name} must be true or false, or left unset to use {default}. '
        f'It is currently {raw!r}.'
    )


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _clean_database_url(raw):
    """Normalise a DATABASE_URL pasted into a hosting dashboard.

    A stray newline, surrounding quotes, or the `psql '...'` wrapper that some
    providers offer alongside the raw string all make the scheme unparseable,
    and the resulting deploy failure points at the parser rather than the paste.
    """
    url = (raw or '').strip()
    if url.startswith('psql '):
        url = url[len('psql '):].strip()
    if len(url) >= 2 and url[0] == url[-1] and url[0] in '"\'':
        url = url[1:-1].strip()
    return url


DATABASE_URL = _clean_database_url(os.environ.get('DATABASE_URL'))

# Fail with a message that names the actual problem. The value is never echoed:
# it carries the database password and this runs straight into the build log.
if DATABASE_URL and not re.match(r'^[a-zA-Z][a-zA-Z0-9+.\-]*://', DATABASE_URL):
    raise RuntimeError(
        'DATABASE_URL is malformed: it must begin with a scheme such as '
        '"postgresql://". Copy the plain connection string from your database '
        'provider - not the "psql" command, a settings snippet, or a partial '
        'selection - and check there is no leading space or newline.'
    )

DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL or f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        # Keep connections between requests, rather than paying to open one
        # every time. On its own that is a trap here: a serverless database
        # suspends itself after a few minutes of no traffic and drops what is
        # open, so the next request picks up a connection that looks fine and
        # is already dead - a server error on whatever page someone happened to
        # arrive at, and only ever the first one after a quiet spell. The health
        # check spends one cheap round trip confirming the connection is alive
        # and quietly reopens it if not.
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Waking a suspended database takes a moment; hanging on it until the host
# gives up on the whole request does not help anyone. Postgres only - SQLite
# does not know this option, and rejects what it does not know.
if DATABASES['default']['ENGINE'].endswith('postgresql'):
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].setdefault(
        'connect_timeout', _env_int('DB_CONNECT_TIMEOUT', 10))


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# The manifest backend serves hashed filenames and refuses to render a page
# referencing a file it has no entry for. That is what you want in production,
# where collectstatic runs during the build. In development it means a fresh
# clone raises on every page until collectstatic has been run once, and adding
# a static file breaks the site until it is run again - so development uses the
# plain backend and reads the files where they lie.
STATICFILES_BACKEND = (
    'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': STATICFILES_BACKEND,
    },
}

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Django's own backend first, so a username - which for a student is their
# student ID - costs nothing extra. The second only ever sees values that look
# like an email address.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'scheduler.auth_backends.EmailBackend',
]


# Outbound mail, for password resets. Everything comes from the environment so
# no credential is committed.
EMAIL_HOST = os.environ.get('EMAIL_HOST', '').strip()
EMAIL_PORT = _env_int('EMAIL_PORT', 587)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# The two ways of encrypting the connection, which belong to different ports:
# STARTTLS on 587, implicit SSL on 465. Django rejects having both on, so
# rather than let that surface as an error at send time, SSL wins - asking for
# it is the deliberate choice, and TLS is only on here because it is the
# default.
EMAIL_USE_SSL = _env_bool('EMAIL_USE_SSL', False)
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', True) and not EMAIL_USE_SSL

# Without this a mail server that accepts the connection and then says nothing
# blocks the worker for as long as the operating system allows, which is far
# longer than the host will wait for the response - so the page dies with no
# explanation rather than reporting that the server did not answer.
EMAIL_TIMEOUT = _env_int('EMAIL_TIMEOUT', 10)
# Mail goes over HTTPS rather than SMTP, which this host blocks - port 587
# times out rather than refusing, which is what blocked looks like from the
# inside. Nothing blocks 443, so an API is preferred wherever a key is present.
# Keys are read from EMAIL_HOST_PASSWORD as well, because that is where they
# land if the provider's SMTP instructions were followed first.
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '').strip()
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '').strip()

SENDING_VIA_BREVO = bool(
    BREVO_API_KEY or EMAIL_HOST_PASSWORD.startswith('xkeysib-'))
SENDING_VIA_RESEND = bool(
    RESEND_API_KEY or EMAIL_HOST_PASSWORD.startswith('re_'))

# Brevo first when both are set. The two differ in what they need before they
# will deliver to anyone other than the account holder: Resend wants a whole
# domain verified through DNS, Brevo wants one address you already own. Only
# the second makes self-service password resets work for students and
# lecturers without owning a domain, which is the point of having mail at all.
if SENDING_VIA_BREVO:
    EMAIL_BACKEND = 'scheduler.mail.BrevoBackend'
elif SENDING_VIA_RESEND:
    EMAIL_BACKEND = 'scheduler.mail.ResendBackend'
elif EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    # Django's default points at an SMTP server on localhost, which does not
    # exist on a hosted box: every send would raise and the reset page would
    # break rather than degrade. Writing the message to the log instead keeps
    # the flow usable - locally while developing, and on a deploy where the
    # provider is not set up yet, where the link can be read out of the logs.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Who the mail comes from. A provider will only send as an address you have
# proved you control, so the placeholder is refused outright - and because a
# reset swallows delivery failures on purpose, refused looks exactly like never
# sent.
#
# Resend keeps one address that works before any domain is verified, so that is
# its fallback and mail works the day the key is pasted in. Brevo has no
# equivalent: the sender has to be the address you verified, so there is
# nothing to guess and the placeholder stands as a marker that it is still to
# be set. MAIL_SENDER_NEEDS_SETTING says which case this is, for the warning on
# the account page.
PLACEHOLDER_FROM_EMAIL = 'KNUST Timetable System <no-reply@example.com>'
FALLBACK_FROM_EMAIL = (
    'KNUST Timetable System <onboarding@resend.dev>' if SENDING_VIA_RESEND
    else PLACEHOLDER_FROM_EMAIL
)
DEFAULT_FROM_EMAIL = (
    os.environ.get('DEFAULT_FROM_EMAIL', '').strip() or FALLBACK_FROM_EMAIL
)
MAIL_SENDER_NEEDS_SETTING = DEFAULT_FROM_EMAIL == PLACEHOLDER_FROM_EMAIL

PASSWORD_RESET_TIMEOUT = _env_int('PASSWORD_RESET_TIMEOUT', 60 * 60 * 24)


# Logging. Without this, an exception in production is a 500 page for the user and
# silence for everyone else. Hosts capture stdout, so a console handler is enough.
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        # Unhandled exceptions, with the traceback rather than just the status line.
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'scheduler': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}


# Production hardening. SECURE_PROXY_SSL_HEADER is required behind Render's proxy —
# without it SECURE_SSL_REDIRECT loops forever and the site is unreachable.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
