# Generated by Django 6.0.7 on 2026-08-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('room', 'timeslot'), name='unique_active_room_timeslot'),
        ),
    ]
