# Generated by Django 6.0.7 on 2026-08-03 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_timetableentry_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reschedulerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': [models.Case(models.When(day='MON', then=0), models.When(day='TUE', then=1), models.When(day='WED', then=2), models.When(day='THU', then=3), models.When(day='FRI', then=4), output_field=models.IntegerField()), 'start_time']},
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('day', 'start_time', 'end_time'), name='unique_day_start_end'),
        ),
    ]
