# Generated by Django 6.0.7 on 2026-08-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_reschedulerequest_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generations_run', models.IntegerField()),
                ('best_fitness', models.FloatField()),
                ('entries_created', models.IntegerField()),
                ('dropped', models.IntegerField(default=0)),
                ('runtime_seconds', models.FloatField()),
                ('history', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
