# Generated by Django 6.0.7 on 2026-08-03 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_generationrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The login account this lecturer signs in with, if they have one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
