# Generated by Django 6.0.7 on 2026-08-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_student_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='index_number',
            field=models.CharField(blank=True, help_text='Their examination index number, if different from the student ID.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400'), ('500', 'Level 500'), ('600', 'Level 600')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(blank=True, help_text='For example, BSc Computer Science.', max_length=120),
        ),
    ]
