# Generated by Django 6.0.7 on 2026-08-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_student_index_number_student_level_student_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='size',
            field=models.PositiveIntegerField(blank=True, help_text='How many students are in this group. Leave blank to count the students assigned to it, or fall back to the course total.', null=True),
        ),
    ]
