# Generated by Django 6.0.7 on 2026-08-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_studentgroup_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='Used only to send a password reset link.', max_length=254),
        ),
    ]
