# Generated by Django 6.0.7 on 2026-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_seed_colleges_and_link_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='lecturer_id',
            field=models.CharField(blank=True, help_text='Their staff number. They need it to set up their own account.', max_length=20, null=True, unique=True, verbose_name='Lecturer ID'),
        ),
    ]
